export default {
    HOME_REFRESH: "HOME_REFRESH",
    HOME_REFRESH_FAIL: "HOME_REFRESH_FAIL",
    HOME_REFRESH_SUCCESS: "HOME_REFRESH_SUCCESS",
    INFO_REFRESH: "INFO_REFRESH",
    INFO_REFRESH_FAIL: "INFO_REFRESH_FAIL",
    INFO_REFRESH_SUCCESS: "INFO_REFRESH_FAIL"
}