export default {
    DEMANDS_REFRESH: "DEMANDS_REFRESH",
    DEMANDS_REFRESH_FAIL: "DEMANDS_REFRESH_FAIL",
    DEMANDS_REFRESH_SUCCESS: "DEMANDS_REFRESH_SUCCESS",
    DEMANDS_LOAD: "DEMANDS_LOAD",
    DEMANDS_LOAD_FAIL: "DEMANDS_LOAD_FAIL",
    DEMANDS_LOAD_SUCCESS: "DEMANDS_LOAD_SUCCESS",
    SHOW_REFRESH: "SHOW_REFRESH",
    SHOW_REFRESH_FAIL: "SHOW_REFRESH_FAIL",
    SHOW_REFRESH_SUCCESS: "SHOW_REFRESH_FAIL",
    SHOW_LOAD: "SHOW_LOAD",
    SHOW_LOAD_FAIL: "SHOW_LOAD_FAIL",
    SHOW_LOAD_SUCCESS: "SHOW_LOAD_SUCCESS",
    UPLOAD_NEW: "UPLOAD_NEW",
    UPLOAD_NEW_SUCCESS: "UPLOAD_NEW_SUCCESS",
    UPLOAD_NEw_FAIL: "UPLOAD_NEW_FAIL"
}